# Generated by Django 4.0.6 on 2022-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_userprofile_alter_post_image_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
